# Generated by Django 2.2.3 on 2019-07-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('type', models.CharField(choices=[('text_label', 'Text Labeling')], max_length=20)),
            ],
        ),
    ]
