# Generated by Django 3.0.7 on 2020-06-22 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('text_label', 'Text Labeling'), ('document_classificaton', 'Document classification')], max_length=50),
        ),
        migrations.CreateModel(
            name='DCDocLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dl_doc', to='annotation.Documents')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dl_label', to='annotation.TlLabels')),
            ],
            options={
                'unique_together': {('document', 'label')},
            },
        ),
    ]
