# Generated by Django 2.2.3 on 2019-08-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_auto_20190805_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='TlLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_background', models.CharField(default='#209cee', max_length=7)),
                ('color_text', models.CharField(default='#ffffff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='annotation.Projects')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='sequence',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='TlSeqLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_start', models.IntegerField(db_index=True)),
                ('offset_stop', models.IntegerField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seqlabel2', to='annotation.TlLabels')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seqlabel1', to='annotation.Sequence')),
            ],
        ),
    ]
