# Generated by Django 2.2.3 on 2019-09-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20190809_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
