# Generated by Django 2.2.3 on 2019-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_documents_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tllabels',
            name='prefix_key',
            field=models.CharField(blank=True, choices=[('ctrl', 'ctrl'), ('shift', 'shift')], max_length=10),
        ),
        migrations.AddField(
            model_name='tllabels',
            name='suffix_key',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f'), ('g', 'g'), ('h', 'h'), ('i', 'i'), ('j', 'j'), ('k', 'k'), ('l', 'l'), ('m', 'm'), ('n', 'n'), ('o', 'o'), ('p', 'p'), ('q', 'q'), ('r', 'r'), ('s', 's'), ('t', 't'), ('u', 'u'), ('v', 'v'), ('w', 'w'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='tllabels',
            unique_together={('project', 'name'), ('project', 'prefix_key', 'suffix_key')},
        ),
    ]
