# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  project_name = 'shanno'
  $memory = 1024
  $cpus = 2

  # config.vm.provider :parallels do |prl|
  #   config.vm.box = "generic/ubuntu1804"
  #   prl.memory = $memory
  #   prl.cpus = $cpus
  #   prl.update_guest_tools = true
  #   prl.name = "#{project_name}"
  # end

  config.vm.provider :virtualbox do |vb|
    config.vm.box = "ubuntu/bionic64"
    vb.memory = $memory
    vb.cpus = $cpus
  end

  # config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.synced_folder "../../", "/home/vagrant/#{project_name}"
end