version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - static-data:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    
  web:
    image: shanno
    environment:
      # SH_DATABASE_URL: "sqlite:////data/db.sqlite3"
      SH_DATABASE_URL: "postgresql://postgres:123456@10.211.55.161/test"
      SH_WORKERS: "4"
      SH_ADMIN_USERNAME: "admin"
      SH_ADMIN_PASSWORD: "123456"
      SH_ADMIN_EMAIL: "admin@admin"
    volumes:
      - static-data:/opt/shanno/staticfiles
      # - ./data:/data/

volumes:
  static-data:
