version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - static-data:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    
  web:
    image: shanno
    environment:
      SH_DATABASE_URL: "sqlite:////data/db.sqlite3"
    volumes:
      - static-data:/opt/shanno/staticfiles
      - ./data:/data/

volumes:
  static-data:
